export const reviewsMock = [
  {
    "text": "{\n  \"name\": \"Miguel Angel Arriagada Contreras\",\n  \"date\": \"22 de febrero de 2025\",\n  \"text\": null,\n  \"stars\": 1,\n  \"reviewDetailedRating\": {\n    \"Food\": null,\n    \"Service\": null,\n    \"Atmosphere\": null\n  },\n  \"reviewContext\": {\n    \"Service\": null,\n    \"Type of food\": \"Comida\",\n    \"Price per customer\": \"25.000-30.000 $\",\n    \"Parking\": null\n  },\n  \"reasons\": [],\n  \"improvements\": []\n}"
  },
  {
    "text": "{\n  \"name\": \"Cristian Orrego\",\n  \"date\": \"18 de febrero de 2025\",\n  \"text\": \"Pésima experiencia, nos atendió un garzón argentino, muy desagradable, pedimos Fetuccinis y eran una pasta de harina sin sabor, les recomiendo que no vayan a esta porquería de restorant, es segunda vez que vamos y la atención y la comida son de restaurant mediocre.\",\n  \"stars\": 1,\n  \"reviewDetailedRating\": \"Comida: 1\\nServicio: 1\\nAmbiente: 1\",\n  \"reviewContext\": \"Servicio:\\nTipo de comida: Comida\\nPrecio por cliente: 20.000-25.000 $\\nEstacionamiento: \",\n  \"reasons\": [\"Atención desagradable del garzón argentino\", \"Fetuccinis sin sabor\", \"Atención y comida mediocre en general\"],\n  \"improvements\": [\"Capacitar al personal para brindar un mejor servicio al cliente\", \"Mejorar la calidad de los platos\", \"Realizar controles de calidad regulares para garantizar la satisfacción del cliente\"]\n}"
  },
  {
    "text": "{\n  \"name\": \"Leelkeed\",\n  \"date\": \"15 de febrero de 2025\",\n  \"text\": \"La reserva no es una reserva, tienes que esperar a que te desocupen una mesa, falta personal para atender a todas las mesas, los tiempos de espera son muy largos (cuando el restaurante está lleno) y es caro... mala experiencia\",\n  \"stars\": 1,\n  \"reviewDetailedRating\": {\n    \"Comida\": 3,\n    \"Servicio\": 1,\n    \"Ambiente\": 1\n  },\n  \"reviewContext\": {\n    \"Tipo de comida\": \"\",\n    \"Precio por cliente\": \"Más de 50.000 $\",\n    \"Servicio\": \"\",\n    \"Estacionamiento\": \"\"\n  },\n  \"reasons\": [\n    \"Excesivos tiempos de espera debido a la falta de personal.\",\n    \"Dificultades para conseguir una mesa a pesar de tener reserva.\",\n    \"Precios elevados.\"\n  ],\n  \"improvements\": [\n    \"Contratar más personal para mejorar el servicio y reducir los tiempos de espera.\",\n    \"Optimizar el sistema de reservas para garantizar la disponibilidad de mesas.\",\n    \"Revisar los precios para hacerlos más competitivos.\"\n  ]\n}"
  },
  {
    "text": "{\n  \"name\": \"Jean Carlos Vera Aliaga\",\n  \"date\": \"14 de febrero de 2025\",\n  \"text\": \"La comida no está mal, esta es mi segunda visita, la atención lenta, espera larga para el primer plato, antes al menos daban focaccia para la espera, ahora nada. Vayan con tiempo, los precios no están mal para el sector.\",\n  \"stars\": 3,\n  \"reviewDetailedRating\": \"Comida: 4\\nServicio: 3\\nAmbiente: 4\",\n  \"reviewContext\": \"Servicio: Comí allí\\nTipo de comida: Comida\\nPrecio por cliente: 20.000-25.000 $\\nEstacionamiento: \",\n  \"reasons\": [\"Atención lenta\", \"Espera larga para el primer plato\", \"Ya no ofrecen focaccia para la espera\"],\n  \"improvements\": [\"Mejorar el tiempo de atención al cliente\", \"Reduzcan el tiempo de espera para los platos\", \"Ofrezcan nuevamente focaccia para amenizar la espera\"]\n}"
  },
  {
    "text": "{\n  \"name\": \"Sebastian Farias\",\n  \"date\": \"07 de febrero de 2025\",\n  \"text\": \"Los garzones pésima atención, ni limpian la mesa, todo lo hacen con malas ganas y se demoran medio día en atenderte\",\n  \"stars\": 3,\n  \"reviewDetailedRating\": null,\n  \"reviewContext\": null,\n  \"reasons\": [\n    \"Pésima atención de los garzones.\",\n    \"No limpian las mesas.\"\n  ],\n  \"improvements\": [\n    \"Mejorar la atención y el servicio de los garzones.\",\n    \"Implementar un protocolo de limpieza de mesas para garantizar la higiene del local.\"\n  ]\n}"
  },
  {
    "text": "{\n  \"name\": \"Colóres Nicole García\",\n  \"date\": \"4 de febrero de 2025\",\n  \"text\": \"Solía ser un lugar muy bueno! La comida está súper con sus precios y es un lugar muy bonito, con un patio fresco e ideal para el verano. Pero la atención se ha empobrecido bastante. Muy lento, los camareros son pesados, esperé una hora por una pizza, para que me dijeran que no tenían la que había pedido, y luego seguir esperando.\",\n  \"stars\": 2,\n  \"reviewDetailedRating\": \"Comida: 4\\nServicio: 2\\nAmbiente: 5\",\n  \"reviewContext\": \"Servicio: \\nTipo de comida: \\nPrecio por cliente: \\nEstacionamiento: \",\n  \"reasons\": [\"Servicio lento\", \"Camareros pesados\", \"Falta de disponibilidad de platos\"],\n  \"improvements\": [\"Mejorar los tiempos de espera\", \"Capacitar al personal para brindar un servicio más atento\", \"Garantizar la disponibilidad de los platos del menú\"]\n}"
  }
];